const TARGET_ADDRESS = '192.168.1.253';
const TARGET_PORT = 3500;
const LOGGING_ENABLED = true;
const OUTPUT_INTERVAL_MS = 500;

export {TARGET_ADDRESS, TARGET_PORT, LOGGING_ENABLED, OUTPUT_INTERVAL_MS}
