const TARGET_ADDRESS = '192.168.1.253';
const TARGET_PORT = 3502;
const LOGGING_ENABLED = true;
const OUTPUT_INTERVAL_MS = 500;
const MOCK_CLIENT = false;

export {TARGET_ADDRESS, TARGET_PORT, LOGGING_ENABLED, MOCK_CLIENT, OUTPUT_INTERVAL_MS}
